### ISSUE TITLE
Mathematical error in tutorial tip

### ISSUE THREAD

**Issue by Snorlaxxo** [Alycse/PepegaCatch#1]
When at the (supposedly) last tutorial task, game tells you to create fusion pepega. It mentions how you need three level 3 pepegas or **nine** level 1 ones, which is false (you need a total of 27 of them, as 9 create just one level 3 pepega). To reproduce, just get to the "Make a fusion pepega" tutorial task". Don't think it's relevant, but I'm using Chrome.

**Comment by Alycse** [comment]
Oh you're right! Thanks, I'll update the text.

**Comment by Alycse** [comment]
I've fixed the tutorial text! Thanks for submitting the report. Unfortunately, Google has to manually review my extension every time I update (even if it's as small as this one), and this usually takes a couple of days. Sorry about this!
