### ISSUE TITLE
Got Scammed

### ISSUE THREAD

**Issue by YouTubeAx** [Alycse/PepegaCatch#11]
I'm not annoyed about it but i did some grinding to get scamazga and it is literally a scam. this is against scamazga's text but could you add an option to unfuse. but it is totally fine if you dont it's just that im mildly salty about losing my amazgas haha

**Comment by Alycse** [comment]
Oh haha, honestly I didn't expect anyone to get a Scamaz this early. But yeah, the purpose of Scamazga was to kind of "scam" the player haha. Thanks for the feedback though!

**Comment by Alycse** [comment]
By the way, if you don't mind me asking, how long did it take you to get a Scamazga, and what's your current overall Army Power? I might actually adjust how much Scamazga hurts the player.

**Comment by YouTubeAx** [comment]
I got scamaz in about a week and my army power was about 80000 but that's not exact as I'm on holiday without my computer but that's the best I can remember.

**Comment by YouTubeAx** [comment]
It was high 200000s before scamaz

**Comment by Alycse** [comment]
Oh okay, thank you for the info!
