### ISSUE TITLE
heal all

### ISSUE THREAD

**Issue by roboaaron1** [Alycse/PepegaCatch#12]
When you get to an endgame level and have like 70 pepegas, they start dying a lot when you grind for Amazgas. I would appreciate a heal all button, as i would be able to one shot anything that comes my way if we could arrange our team, and my low level pepegas keep taking the bullet. It's just not fun to always heal each pepega indiviually. Thanks in advance.

**Comment by Alycse** [comment]
Thanks for the feedback! I'll be adding a **heal all** button in the next update.
