### ISSUE TITLE
game corrupted

### ISSUE THREAD

**Issue by roboaaron1** [Alycse/PepegaCatch#14]
I really like pepega catch. I had billions of iq and 70 slots. I had a lvl 3 amazga and nearly another lvl 2 amazga, plus a lot of fusions and pepegas. Suddenly, the extension disapeared. I went into manage extensions and it said the extension was corrupted. I clicked repair, and reopened it when it was done. I lost everything. I dont know what to do know, maybe some sort of secret password you can make and give to me to type in and get similiar stuff back? Or maybe I just have to deal with it, and hope you can fix it so it doesn't happen to anyone else. And no, I don't have anything that could interfere with any other extensions. Bye.

**Comment by Alycse** [comment]
Hey I'm sorry about this! I'll try to fix it as soon as I can.
Did you do anything when this happened or were you just idle?

I'll be trying to make a secret password-like feature that should get your stuff back.

**Comment by Alycse** [comment]
Also, did some of your other extensions get corrupted too, or just this one?

**Comment by Alycse** [comment]
I've created the Save and Load feature!
https://i.imgur.com/MZyBWhs.png
Clicking the **Get Save Data** button will download a text file to your computer.
Clicking the **Load Data** button will show the **load input box**.
https://i.imgur.com/4uAscoL.png
Simply copy and paste the text from the save text file in that box to load it.

The save data text file is in _json_ format so it can be easily modified. This means I should be able to create a save file for you that will be somewhat close to your lost progress (what you can remember, at least). Just tell me how much IQ and what Pepegas you want back and I'll try my best to recreate to it! I'll then give you the text to load into your game.

Unfortunately though, like before, Google takes a long time to update the extension. If you wish, you can download the zip file from github, extract it to a folder, then load it by typing _chrome://extensions/_ to your address bar, and clicking the **Load Unpacked** button on the top left. Find the folder in your pc and click **Select Folder**. Make sure you disable the officially-downloaded extension first, or else you'll have two instances of the game running at the same time!

If you're using the Firefox version, however, it should already be updated. _(v0.4.0)_

**Comment by roboaaron1** [comment]
Thank you for fixing it so quickly. None of my other extensions got corrupted, just pepega catch. I was just using my computer, and had used pepega catch like 5 minutes ago. It just randomly happened. Yes, I was in version 0.3.4 because I use google chrome. I was pepega legend gold. I had around 5 bill iq, and i had 71 slots, and a lvl 3 amazga and a level 2. I had a tylerga, a greekgax, a ninjaga, a xqga, a shroudga, and a triga. i had a orange pepega, a hunter, a wizard, a lvl 3 jamga, a lvl 3 fastga, a forsenga, a doctor pepega and im sure i can get the rest myself. Thank you.

**Comment by Alycse** [comment]
Okay, I'll quickly make a save file for you. Are you gonna download the latest version with the save/load functionality here from GitHub? If so, let me know if you need help in installing it. I forgot to mention that you have to turn on **Developer Mode** in the top right in _chrome://extensions/_ to be able to see the **Load Unpacked** button. Once the official extension on the Chrome Web Store gets updated, you can easily just Save your progress on the downloaded one and load it on the official one.

I'm creating the save data right now, should take maybe a few minutes.

I'm really sorry for the inconvenience by the way!

**Comment by roboaaron1** [comment]
Thank you. Also I think you should be able to download the save data, and upload it to the app. Otherwise the save data will just corrupt too.

**Comment by roboaaron1** [comment]
Do i need to unzip the folder?

**Comment by Alycse** [comment]
Yeah, the save data is actually downloaded to your computer. It will be a text file (.txt) with the save information written on it (in json format). You can copy the text from that file and paste it on the Load box in the game.

And yes, you need to unzip the folder.

**Comment by roboaaron1** [comment]
Thanks. Sorry to rush you all about doing this.

**Comment by roboaaron1** [comment]
I did everything you told me, is there anything else I need to do now? Do i enable the extension again? Or do i click pack extension now?

**Comment by Alycse** [comment]
Haha it's okay! I'm not super busy at the moment so it's fine, and I don't want my users to have a bad experience.

You should click the Load Unpacked button, and then select the folder you extracted from the zip file.

**Comment by roboaaron1** [comment]
Do I clicked packed if I want to play the normal version? And thanks for all your help.

**Comment by Alycse** [comment]
By normal version, you mean the one from Chrome Web Store?

**Comment by roboaaron1** [comment]
Yea. And also, here's my email in case thats how you plan to give me the txt file:
retartedpyro64@gmail.com

**Comment by roboaaron1** [comment]
I'll delete that message soon though because I dont want my email open to everyone. Just tell me when you've seen it.

**Comment by Alycse** [comment]
You can just install it from the Chrome Web Store if you wish to play the normal, official version. And yeah, I've seen the email!
The one on the store is the old version though (v0.3.4) since Google hasn't published the updated one yet, so it won't have the save/load feature.

**Comment by roboaaron1** [comment]
Thanks, I really appreciate it.

**Comment by Alycse** [comment]
Hey, I've sent the email with the save file. Just copy the entire text in that text file and paste it on the Load box.
You may modify the values too if you wish. I might not have gotten the Pepegas' powers correctly since a pepega's power is randomly generated when you encounter it on a website.
Let me know if there's something wrong with the save or if you want something changed/added/removed!
