### ISSUE TITLE
FANDOM page

### ISSUE THREAD

**Issue by YouTubeAx** [Alycse/PepegaCatch#15]
Me and my friend are both proud players of pepega catch and we have decided to make a fandom for it. the link is: https://pepega-catch.fandom.com/wiki/Pepega_Catch_Wiki and I decided to post this in order to get permission to be official.

Thanks,
Ax

**Comment by Alycse** [comment]
Hey, this is great! Thank you for making this!
And yeah, you have my complete permission. You can do whatever you wish
with that fandom.

I'm glad you and your friend are having fun with the game!
