### ISSUE TITLE
How to get others.

### ISSUE THREAD

**Issue by YouTubeAx** [Alycse/PepegaCatch#17]
I have been trying to find out ways to get all of the different pepegas listed in the images ( https://github.com/Alycse/PepegaCatch/tree/master/images/pepegas/ ) and I don't seem to be finding them. Is there any clues or specific websites or are they just super rare or haven't been added into the game yet.

**Comment by Alycse** [comment]
All the Pepegas listed there have been added to the game, it's just that some of them are only present in more obscure websites. I'll be adding a "hint" feature soon though!  I might have made some of the Pepegas "too obscure" haha.
