### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by roboaaron1** [Alycse/PepegaCatch#19]
Your file was not foundIt may have been moved or deleted.
ERR_FILE_NOT_FOUND
Thats the message I get when I open pepega catch.

**Comment by Alycse** [comment]
I'll look into this. May I see a screenshot of the error? I would like to know how and where the error appears.

Thanks for reporting the bug!

**Comment by Alycse** [comment]
Also, have you completely uninstalled the downloaded version of the game? It is possible that you are opening the popup button of the downloaded version (which you probably have deleted the files of) and not the one from the chrome web store, but I'm still looking into it!

**Comment by roboaaron1** [comment]
![image](https://user-images.githubusercontent.com/54919951/67264169-0b495c00-f4f6-11e9-8a21-4a05924bb09d.png)
Also this happens to me instead of a pepega spawning.
![image](https://user-images.githubusercontent.com/54919951/67264193-1c926880-f4f6-11e9-8435-2526626bfcf7.png)
And yes, I deleted the github version a while ago. I believe I have a fairly recent save data copy though, so it should be fine. But yeah, I have no idea why this happened.

**Comment by roboaaron1** [comment]
The second image is meant to look like text, thats one of the glitches in the game. It just shows that on any page where this is supposed to be a pepega.

**Comment by roboaaron1** [comment]
It says this in manage extensions:
Stack error
_generated_background_page.html:0 (anonymous function)

**Comment by Alycse** [comment]
Does this still occur when you reinstall the extension and load your save data?

**Comment by roboaaron1** [comment]
No, it doesn't.
