### ISSUE TITLE
Weird behaviour of the rank progression system

### ISSUE THREAD

**Issue by Snorlaxxo** [Alycse/PepegaCatch#2]
After Playing for a while, I noticed that my rank prerequsite is lower than my actual IQ, and I didn't get new rank for passing it. Right after that I spent some IQ on upgrade, setting me behind 20k tier, that I lost, then got back, and then I got 20k prerequisite after I got to 20k. I don' know exact steps to reproduce that, as I'm not exactly sure what made it start in the first place. I'm using chrome.
![image](https://user-images.githubusercontent.com/30737231/63775351-6dfbee00-c8df-11e9-93b3-91a9e3bde262.png)

**Comment by Alycse** [comment]
I'll look into this. Thanks for letting me know!

**Comment by Alycse** [comment]
I've fixed the rank IQ prerequisites! Unfortunately, it takes a couple of days for Google to update my extension because they have to manually review it every time I update. I'm sorry about this!
