### ISSUE TITLE
Can you fing every pepega on a page or are some fusion locked?

### ISSUE THREAD

**Issue by YouTubeAx** [Alycse/PepegaCatch#20]

**Comment by Alycse** [comment]
Could you elaborate further? What do you mean "fusion locked"?
And some Pepegas can only be found on certain pages.

**Comment by YouTubeAx** [comment]
Fusion locked by you can't find it anywhere. And if possible could you provide a list of those certain pages.. 😏

**Comment by Alycse** [comment]
Oh yes, there are a few types of Pepega that can only be fused. I'll be making a hint system or a list soon.
