### ISSUE TITLE
scuffed btw PepeLaugh

### ISSUE THREAD

**Issue by TormentDubz** [Alycse/PepegaCatch#21]
**Describe the bug**
Most Pepegas disappear from army with no explanation.

**To Reproduce**
Happens at completely arbitrary intervals.

**Expected behavior**
Pepegas should not disappear without being manually released

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 70.0.1

**Comment by Alycse** [comment]
I'll look into it. Thanks for reporting the bug.
May I ask if they return or do they disappear forever?

**Comment by TormentDubz** [comment]
They disappear forever. Version is 0.8.2

**Comment by Alycse** [comment]
Were you just idle when the Pepegas disappeared, or did you interact with something?
And is there a pattern as to which Pepegas disappear? Like, were they all Level 3, a particular type of Pepega, dead, or just completely random?
I can't seem to replicate the issue on Firefox.
Also, was the popup opened or closed when it happened?

It might also help if you give me a list of which Pepegas you have, your IQ count, and your army slot count. I could then simulate your game and try to find the problem through that.

Thank you!

**Comment by TormentDubz** [comment]
I don't think I was idle. All the ones that disappeared were past slot 5 or 6 in the army and the popup was closed.
My IQ is currently 1.48bil but it was probably around 500 mil when it happened last, and I have 18 slots. I currently have level 3 joy, level 1 Okayga, level 1 Pepege, level 2 aim and level 3 pride

**Comment by Alycse** [comment]
Okay, thank you for the info! I'll be looking into it.
