### ISSUE TITLE
Pepegas creating new rows after going one row down because of long numbers

### ISSUE THREAD

**Issue by Snorlaxxo** [Alycse/PepegaCatch#3]
Basically, if your pepegas has high enough numbers, the last one will be pushed one row down, and then, since it's 5th (or 10th, 15th etc.), it makes next ones create second row with only it being in the previous row.
![image](https://user-images.githubusercontent.com/30737231/63839016-bd452b80-c97e-11e9-88f0-2f018f0c2a2c.png)

**Comment by Alycse** [comment]
Thanks for reporting this. Fixing it right now!

**Comment by Alycse** [comment]
I've fixed the layout! This is how it will look like now when a Pepega has huge numbers:

![DEBUG](https://user-images.githubusercontent.com/13681507/63850166-11273300-c9c6-11e9-997f-fd7ded88b4f6.png)

Again though, it's gonna take Google a couple of days to update the extension, so I'm really sorry about this. If you're using the Firefox version, however, it should be updated very shortly!
