### ISSUE TITLE
pepega hunter

### ISSUE THREAD

**Issue by roboaaron1** [Alycse/PepegaCatch#9]
the pepega hunter is broken, it doesnt show in the party properly, its description takes up space of the menu, and you cant see its picture. please fix.

**Comment by roboaaron1** [comment]
when you fuse pepega's together, it doesnt fuse all of their power together. for example, if i fuse three 11,000 power level 400 iq pepegas into a level 2,  it only has 22,000 instead of the altogether 33,000. this makes power downgrade in fusion. thx for reading, if this is on purpose than dont worry about it

**Comment by Alycse** [comment]
Thanks for the report! The Pepega Hunter image should be fixed in the next update.
And yeah, combining three 11k Pepegas to level it up will only power it up to 22k instead of 33k. The upside of this is that you get an additional slot for another Pepega.
